name: Mr Bread's charmber
permalink: /:categories/:year/:month/:day/:title
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
safe: true
paginate: 5
BASE_PATH : false
ASSET_PATH : false
archive_path: /archive.html
categories_path : /categories.html
tags_path : /tags.html
markdown: rdiscount
#highlighter: rouge
# UTF-8
extensions: [fenced_code_blocks]
